# Generated by Django 4.2.5 on 2024-01-27 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0003_fishtag_spot_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishtag',
            old_name='slug',
            new_name='tag',
        ),
    ]
