# Generated by Django 4.2.5 on 2024-01-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_merge_20240102_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='Стаж'
            ),
        ),
    ]
