# Generated by Django 4.2.5 on 2024-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_user_experience_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                default=True, verbose_name='Пользователь активен'
            ),
        ),
    ]
