# Generated by Django 4.2.5 on 2024-03-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid_activate',
            field=models.CharField(
                blank=True,
                help_text='уникальная штука для активации',
                max_length=50,
                null=True,
                verbose_name='UUID',
            ),
        ),
    ]
