# Generated by Django 4.2.5 on 2024-03-27 08:49

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                default='/avatars/base.jpg',
                upload_to=users.models.User.path_to_save,
                verbose_name='Аватарка',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='день и время, когда пользователь зарегистрировался',
                null=True,
                verbose_name='Дата присоединения',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                help_text='почтовый адрес',
                max_length=254,
                unique=True,
                verbose_name='Почта',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name='Имя'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name='Фамилия'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                help_text='имя отображаемое для всех пользователей (nickname).\nДопустимые символы: латиница, цифры, @|.|+|-|_',
                max_length=25,
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(25),
                    django.core.validators.MinLengthValidator(4),
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                ],
                verbose_name='Пользовательское имя',
            ),
        ),
    ]
