# Generated by Django 4.2.5 on 2024-03-27 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_alter_user_avatar_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token_activate',
            new_name='token',
        ),
    ]
