# Generated by Django 4.2.5 on 2024-03-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_rename_token_activate_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name='Стаж в годах'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                blank=True,
                default='отсутствует',
                max_length=150,
                null=True,
                verbose_name='Имя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=True,
                default='отсутствует',
                max_length=150,
                null=True,
                verbose_name='Фамилия',
            ),
        ),
    ]
