# Generated by Django 4.2.5 on 2024-03-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rating', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingimages',
            name='spot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rating_images',
                related_query_name='rating_images',
                to='rating.spotrating',
                verbose_name='Место|Водоём',
            ),
        ),
    ]
